name: Update # Name of action

on:
  workflow_dispatch: # allow manual run
  schedule:
    - cron: '0 3 * * *' # schedule run

jobs:
  build:
    runs-on: ubuntu-latest # Set build environment
    steps: # Steps to update
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4 # Configure actions to setup python
        with:
          python-version: "3.x" # Set python version

      - name: Install dependencies # Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update # Upadate (Check, replace) repo
        working-directory: ./script
        run: |
          python fetch.py --production

      - name: Apply changes # Apply changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update version to latest"